"""Tanitim videosunun metinleri — 14 dil.

EN tabandir; diger diller yalnizca cevirdiklerini listeler ve eksik anahtar
otomatik olarak Ingilizce'ye duser (paneldeki ceviri sistemiyle ayni kural).

Metinler KISA tutuluyor: 1920x1080'de tek satira sigmali ve okunacak sure
saniyelerle olculuyor.
"""

STRINGS = {}

STRINGS["en"] = {
    "tagline1": "Keeps your free Aternos server",
    "tagline2": "online around the clock.",
    "eyebrow_problem": "THE PROBLEM",
    "problem_h": "Empty servers get put to sleep.",
    "problem_p": "Getting one back means the queue — every single time.",
    "eyebrow_queue": "WHAT A SCRIPT CANNOT DO",
    "queue_h": "It confirms the queue for you.",
    "eta": "~14 min",
    "confirmed": "your turn — confirmed automatically",
    "queue_p1": "Aternos opens a ~30 second window when your turn comes.",
    "queue_p2": "Miss it and you go to the back. aterkeep never misses it.",
    "eyebrow_setup": "SETUP, ONCE",
    "login_h": "No cookie copying.",
    "f_user": "Aternos username",
    "f_pass": "Aternos password",
    "login_old": "F12 → Network → copy the cookie header",
    "login_new": "Sign in once. It renews the session itself, every 30 days.",
    "eyebrow_result": "RESULT",
    "online_h": "Online. And it stays that way.",
    "st_online": "ONLINE",
    "st_offline": "OFFLINE",
    "st_queue": "IN QUEUE",
    "m_players": "PLAYERS",
    "m_tps": "TPS",
    "m_ram": "RAM",
    "eyebrow_what": "WHAT YOU GET",
    "f1_t": "One binary",
    "f1_d": "No runtime. Windows, Linux, macOS.",
    "f2_t": "Anti-idle bot",
    "f2_d": "Joins so the server isn't shut down.",
    "f3_t": "Encrypted session",
    "f3_d": "AES-256-GCM, no key on disk.",
    "f4_t": "14 languages",
    "f4_d": "Password-protected panel, pure HTTP.",
    "cta_h": "Want it?",
    "cta_lic": "Commercial, source-available licence.",
    "cta_tos": "Aternos' terms forbid keep-alive bots — your account is at risk.",
    "cta_aff": "Not affiliated with Aternos GmbH or Mojang Studios.",
}

STRINGS["tr"] = {
    "tagline1": "Ücretsiz Aternos sunucunu",
    "tagline2": "kesintisiz açık tutar.",
    "eyebrow_problem": "SORUN",
    "problem_h": "Boş sunucular uykuya alınır.",
    "problem_p": "Geri açmak her seferinde kuyruğa girmek demek.",
    "eyebrow_queue": "BİR SCRİPTİN YAPAMADIĞI ŞEY",
    "queue_h": "Sırayı senin yerine onaylar.",
    "eta": "~14 dk",
    "confirmed": "sıra geldi — otomatik onaylandı",
    "queue_p1": "Sıra sana geldiğinde Aternos ~30 saniyelik bir pencere açar.",
    "queue_p2": "Kaçırırsan en sona düşersin. aterkeep kaçırmaz.",
    "eyebrow_setup": "KURULUM, BİR KEZ",
    "login_h": "Çerez kopyalamak yok.",
    "f_user": "Aternos kullanıcı adı",
    "f_pass": "Aternos parolası",
    "login_old": "F12 → Network → cookie başlığını kopyala",
    "login_new": "Bir kez giriş yap. Oturumu 30 günde bir kendi yeniler.",
    "eyebrow_result": "SONUÇ",
    "online_h": "Açık. Ve açık kalıyor.",
    "st_online": "AÇIK",
    "st_offline": "KAPALI",
    "st_queue": "SIRADA",
    "m_players": "OYUNCU",
    "m_tps": "TPS",
    "m_ram": "RAM",
    "eyebrow_what": "NE ALIYORSUN",
    "f1_t": "Tek dosya",
    "f1_d": "Kurulum yok. Windows, Linux, macOS.",
    "f2_t": "Anti-idle bot",
    "f2_d": "Girer, sunucu boş diye kapanmaz.",
    "f3_t": "Şifreli oturum",
    "f3_d": "AES-256-GCM, diskte anahtar yok.",
    "f4_t": "14 dil",
    "f4_d": "Parola korumalı panel, saf HTTP.",
    "cta_h": "İster misin?",
    "cta_lic": "Ticari, kaynağı görülebilir lisans.",
    "cta_tos": "Aternos kuralları keep-alive botlarını yasaklar — hesabın risk altında.",
    "cta_aff": "Aternos GmbH veya Mojang Studios ile ilişkisi yoktur.",
}

STRINGS["de"] = {
    "tagline1": "Hält deinen kostenlosen Aternos-Server",
    "tagline2": "rund um die Uhr online.",
    "eyebrow_problem": "DAS PROBLEM",
    "problem_h": "Leere Server werden schlafen gelegt.",
    "problem_p": "Zurückholen heißt: jedes Mal in die Warteschlange.",
    "eyebrow_queue": "WAS EIN SKRIPT NICHT KANN",
    "queue_h": "Es bestätigt die Warteschlange für dich.",
    "eta": "~14 Min",
    "confirmed": "du bist dran — automatisch bestätigt",
    "queue_p1": "Aternos öffnet ein Fenster von etwa 30 Sekunden.",
    "queue_p2": "Verpasst du es, gehst du nach hinten. aterkeep verpasst es nie.",
    "eyebrow_setup": "EINMALIGE EINRICHTUNG",
    "login_h": "Kein Cookie-Kopieren.",
    "f_user": "Aternos-Benutzername",
    "f_pass": "Aternos-Passwort",
    "login_old": "F12 → Network → cookie-Zeile kopieren",
    "login_new": "Einmal anmelden. Die Sitzung erneuert sich alle 30 Tage selbst.",
    "eyebrow_result": "ERGEBNIS",
    "online_h": "Online. Und bleibt es.",
    "st_online": "ONLINE",
    "st_offline": "OFFLINE",
    "st_queue": "IN WARTESCHLANGE",
    "m_players": "SPIELER",
    "eyebrow_what": "WAS DU BEKOMMST",
    "f1_t": "Eine Datei",
    "f1_d": "Keine Laufzeit. Windows, Linux, macOS.",
    "f2_t": "Anti-Idle-Bot",
    "f2_d": "Tritt bei, damit nicht abgeschaltet wird.",
    "f3_t": "Verschlüsselte Sitzung",
    "f3_d": "AES-256-GCM, kein Schlüssel auf der Platte.",
    "f4_t": "14 Sprachen",
    "f4_d": "Passwortgeschütztes Panel, reines HTTP.",
    "cta_h": "Interesse?",
    "cta_lic": "Kommerzielle Lizenz, Quelltext einsehbar.",
    "cta_tos": "Aternos verbietet Keep-Alive-Bots — dein Konto ist gefährdet.",
    "cta_aff": "Nicht mit Aternos GmbH oder Mojang Studios verbunden.",
}

STRINGS["fr"] = {
    "tagline1": "Garde ton serveur Aternos gratuit",
    "tagline2": "en ligne 24 heures sur 24.",
    "eyebrow_problem": "LE PROBLÈME",
    "problem_h": "Les serveurs vides sont mis en veille.",
    "problem_p": "Le relancer, c'est la file d'attente — à chaque fois.",
    "eyebrow_queue": "CE QU'UN SCRIPT NE FAIT PAS",
    "queue_h": "Il confirme la file à ta place.",
    "eta": "~14 min",
    "confirmed": "c'est ton tour — confirmé automatiquement",
    "queue_p1": "Aternos ouvre une fenêtre d'environ 30 secondes.",
    "queue_p2": "Si tu la rates, tu repars à la fin. aterkeep ne la rate jamais.",
    "eyebrow_setup": "INSTALLATION, UNE FOIS",
    "login_h": "Pas de cookie à copier.",
    "f_user": "Identifiant Aternos",
    "f_pass": "Mot de passe Aternos",
    "login_old": "F12 → Network → copier l'en-tête cookie",
    "login_new": "Connecte-toi une fois. La session se renouvelle tous les 30 jours.",
    "eyebrow_result": "RÉSULTAT",
    "online_h": "En ligne. Et ça le reste.",
    "st_online": "EN LIGNE",
    "st_offline": "HORS LIGNE",
    "st_queue": "EN FILE",
    "m_players": "JOUEURS",
    "eyebrow_what": "CE QUE TU OBTIENS",
    "f1_t": "Un seul fichier",
    "f1_d": "Aucun runtime. Windows, Linux, macOS.",
    "f2_t": "Bot anti-idle",
    "f2_d": "Rejoint pour éviter l'arrêt automatique.",
    "f3_t": "Session chiffrée",
    "f3_d": "AES-256-GCM, aucune clé sur le disque.",
    "f4_t": "14 langues",
    "f4_d": "Panneau protégé par mot de passe, HTTP pur.",
    "cta_h": "Ça t'intéresse ?",
    "cta_lic": "Licence commerciale, code consultable.",
    "cta_tos": "Aternos interdit les bots de maintien — ton compte est en risque.",
    "cta_aff": "Sans lien avec Aternos GmbH ni Mojang Studios.",
}

STRINGS["es"] = {
    "tagline1": "Mantiene tu servidor Aternos gratuito",
    "tagline2": "en línea las 24 horas.",
    "eyebrow_problem": "EL PROBLEMA",
    "problem_h": "Los servidores vacíos se apagan.",
    "problem_p": "Recuperarlo significa la cola — cada vez.",
    "eyebrow_queue": "LO QUE UN SCRIPT NO HACE",
    "queue_h": "Confirma la cola por ti.",
    "eta": "~14 min",
    "confirmed": "es tu turno — confirmado automáticamente",
    "queue_p1": "Aternos abre una ventana de unos 30 segundos.",
    "queue_p2": "Si la pierdes, vuelves al final. aterkeep nunca la pierde.",
    "eyebrow_setup": "INSTALACIÓN, UNA VEZ",
    "login_h": "Sin copiar cookies.",
    "f_user": "Usuario de Aternos",
    "f_pass": "Contraseña de Aternos",
    "login_old": "F12 → Network → copiar la cabecera cookie",
    "login_new": "Inicia sesión una vez. La sesión se renueva sola cada 30 días.",
    "eyebrow_result": "RESULTADO",
    "online_h": "En línea. Y sigue así.",
    "st_online": "EN LÍNEA",
    "st_offline": "APAGADO",
    "st_queue": "EN COLA",
    "m_players": "JUGADORES",
    "eyebrow_what": "QUÉ OBTIENES",
    "f1_t": "Un solo binario",
    "f1_d": "Sin runtime. Windows, Linux, macOS.",
    "f2_t": "Bot anti-idle",
    "f2_d": "Entra para que no lo apaguen.",
    "f3_t": "Sesión cifrada",
    "f3_d": "AES-256-GCM, sin clave en disco.",
    "f4_t": "14 idiomas",
    "f4_d": "Panel con contraseña, HTTP puro.",
    "cta_h": "¿Lo quieres?",
    "cta_lic": "Licencia comercial, código visible.",
    "cta_tos": "Aternos prohíbe los bots keep-alive — tu cuenta está en riesgo.",
    "cta_aff": "Sin relación con Aternos GmbH ni Mojang Studios.",
}

STRINGS["it"] = {
    "tagline1": "Tiene il tuo server Aternos gratuito",
    "tagline2": "online 24 ore su 24.",
    "eyebrow_problem": "IL PROBLEMA",
    "problem_h": "I server vuoti vengono spenti.",
    "problem_p": "Riaccenderlo significa la coda — ogni volta.",
    "eyebrow_queue": "QUELLO CHE UNO SCRIPT NON FA",
    "queue_h": "Conferma la coda al posto tuo.",
    "eta": "~14 min",
    "confirmed": "tocca a te — confermato automaticamente",
    "queue_p1": "Aternos apre una finestra di circa 30 secondi.",
    "queue_p2": "Se la perdi torni in fondo. aterkeep non la perde mai.",
    "eyebrow_setup": "INSTALLAZIONE, UNA VOLTA",
    "login_h": "Niente cookie da copiare.",
    "f_user": "Nome utente Aternos",
    "f_pass": "Password Aternos",
    "login_old": "F12 → Network → copia l'intestazione cookie",
    "login_new": "Accedi una volta. La sessione si rinnova da sola ogni 30 giorni.",
    "eyebrow_result": "RISULTATO",
    "online_h": "Online. E ci resta.",
    "st_online": "ONLINE",
    "st_offline": "OFFLINE",
    "st_queue": "IN CODA",
    "m_players": "GIOCATORI",
    "eyebrow_what": "COSA OTTIENI",
    "f1_t": "Un solo file",
    "f1_d": "Nessun runtime. Windows, Linux, macOS.",
    "f2_t": "Bot anti-idle",
    "f2_d": "Entra così non viene spento.",
    "f3_t": "Sessione cifrata",
    "f3_d": "AES-256-GCM, nessuna chiave su disco.",
    "f4_t": "14 lingue",
    "f4_d": "Pannello protetto da password, HTTP puro.",
    "cta_h": "Ti interessa?",
    "cta_lic": "Licenza commerciale, sorgente consultabile.",
    "cta_tos": "Aternos vieta i bot keep-alive — il tuo account è a rischio.",
    "cta_aff": "Non affiliato ad Aternos GmbH o Mojang Studios.",
}

STRINGS["pt"] = {
    "tagline1": "Mantém o teu servidor Aternos gratuito",
    "tagline2": "online 24 horas por dia.",
    "eyebrow_problem": "O PROBLEMA",
    "problem_h": "Servidores vazios são desligados.",
    "problem_p": "Voltar a ligá-lo significa a fila — sempre.",
    "eyebrow_queue": "O QUE UM SCRIPT NÃO FAZ",
    "queue_h": "Confirma a fila por ti.",
    "eta": "~14 min",
    "confirmed": "é a tua vez — confirmado automaticamente",
    "queue_p1": "O Aternos abre uma janela de cerca de 30 segundos.",
    "queue_p2": "Se falhares, voltas ao fim. O aterkeep nunca falha.",
    "eyebrow_setup": "INSTALAÇÃO, UMA VEZ",
    "login_h": "Sem copiar cookies.",
    "f_user": "Utilizador Aternos",
    "f_pass": "Palavra-passe Aternos",
    "login_old": "F12 → Network → copiar o cabeçalho cookie",
    "login_new": "Entra uma vez. A sessão renova-se sozinha a cada 30 dias.",
    "eyebrow_result": "RESULTADO",
    "online_h": "Online. E assim fica.",
    "st_online": "ONLINE",
    "st_offline": "DESLIGADO",
    "st_queue": "NA FILA",
    "m_players": "JOGADORES",
    "eyebrow_what": "O QUE RECEBES",
    "f1_t": "Um único ficheiro",
    "f1_d": "Sem runtime. Windows, Linux, macOS.",
    "f2_t": "Bot anti-idle",
    "f2_d": "Entra para não ser desligado.",
    "f3_t": "Sessão cifrada",
    "f3_d": "AES-256-GCM, sem chave no disco.",
    "f4_t": "14 idiomas",
    "f4_d": "Painel protegido por palavra-passe, HTTP puro.",
    "cta_h": "Queres?",
    "cta_lic": "Licença comercial, código visível.",
    "cta_tos": "O Aternos proíbe bots keep-alive — a tua conta corre risco.",
    "cta_aff": "Sem ligação à Aternos GmbH ou à Mojang Studios.",
}

STRINGS["ru"] = {
    "tagline1": "Держит твой бесплатный сервер Aternos",
    "tagline2": "онлайн круглые сутки.",
    "eyebrow_problem": "ПРОБЛЕМА",
    "problem_h": "Пустые серверы усыпляют.",
    "problem_p": "Вернуть его — значит снова встать в очередь.",
    "eyebrow_queue": "ЧЕГО НЕ УМЕЕТ СКРИПТ",
    "queue_h": "Он подтверждает очередь за тебя.",
    "eta": "~14 мин",
    "confirmed": "твоя очередь — подтверждено автоматически",
    "queue_p1": "Aternos даёт окно примерно в 30 секунд.",
    "queue_p2": "Пропустишь — уйдёшь в конец. aterkeep не пропускает.",
    "eyebrow_setup": "НАСТРОЙКА, ОДИН РАЗ",
    "login_h": "Никаких копирований cookie.",
    "f_user": "Имя пользователя Aternos",
    "f_pass": "Пароль Aternos",
    "login_old": "F12 → Network → скопировать заголовок cookie",
    "login_new": "Войди один раз. Сессия обновляется сама каждые 30 дней.",
    "eyebrow_result": "РЕЗУЛЬТАТ",
    "online_h": "Онлайн. И остаётся таким.",
    "st_online": "ОНЛАЙН",
    "st_offline": "ОФЛАЙН",
    "st_queue": "В ОЧЕРЕДИ",
    "m_players": "ИГРОКИ",
    "eyebrow_what": "ЧТО ТЫ ПОЛУЧАЕШЬ",
    "f1_t": "Один файл",
    "f1_d": "Без рантайма. Windows, Linux, macOS.",
    "f2_t": "Анти-простой бот",
    "f2_d": "Заходит, чтобы сервер не выключили.",
    "f3_t": "Шифрованная сессия",
    "f3_d": "AES-256-GCM, ключа на диске нет.",
    "f4_t": "14 языков",
    "f4_d": "Панель с паролем, чистый HTTP.",
    "cta_h": "Нужен?",
    "cta_lic": "Коммерческая лицензия, исходники открыты для просмотра.",
    "cta_tos": "Правила Aternos запрещают такие боты — аккаунт под риском.",
    "cta_aff": "Не связан с Aternos GmbH или Mojang Studios.",
}

STRINGS["nl"] = {
    "tagline1": "Houdt je gratis Aternos-server",
    "tagline2": "de klok rond online.",
    "eyebrow_problem": "HET PROBLEEM",
    "problem_h": "Lege servers worden slapend gezet.",
    "problem_p": "Terughalen betekent de wachtrij — elke keer.",
    "eyebrow_queue": "WAT EEN SCRIPT NIET KAN",
    "queue_h": "Het bevestigt de wachtrij voor je.",
    "eta": "~14 min",
    "confirmed": "jij bent aan de beurt — automatisch bevestigd",
    "queue_p1": "Aternos opent een venster van ongeveer 30 seconden.",
    "queue_p2": "Mis je het, dan ga je achteraan. aterkeep mist het nooit.",
    "eyebrow_setup": "EENMALIGE INSTALLATIE",
    "login_h": "Geen cookies kopiëren.",
    "f_user": "Aternos-gebruikersnaam",
    "f_pass": "Aternos-wachtwoord",
    "login_old": "F12 → Network → cookie-regel kopiëren",
    "login_new": "Eén keer aanmelden. De sessie vernieuwt zichzelf elke 30 dagen.",
    "eyebrow_result": "RESULTAAT",
    "online_h": "Online. En dat blijft zo.",
    "st_online": "ONLINE",
    "st_offline": "OFFLINE",
    "st_queue": "IN WACHTRIJ",
    "m_players": "SPELERS",
    "eyebrow_what": "WAT JE KRIJGT",
    "f1_t": "Eén bestand",
    "f1_d": "Geen runtime. Windows, Linux, macOS.",
    "f2_t": "Anti-idle bot",
    "f2_d": "Sluit aan zodat hij niet afsluit.",
    "f3_t": "Versleutelde sessie",
    "f3_d": "AES-256-GCM, geen sleutel op schijf.",
    "f4_t": "14 talen",
    "f4_d": "Paneel met wachtwoord, puur HTTP.",
    "cta_h": "Interesse?",
    "cta_lic": "Commerciële licentie, broncode inzichtelijk.",
    "cta_tos": "Aternos verbiedt keep-alive bots — je account loopt risico.",
    "cta_aff": "Geen band met Aternos GmbH of Mojang Studios.",
}

STRINGS["pl"] = {
    "tagline1": "Utrzymuje twój darmowy serwer Aternos",
    "tagline2": "online przez całą dobę.",
    "eyebrow_problem": "PROBLEM",
    "problem_h": "Puste serwery są usypiane.",
    "problem_p": "Przywrócenie oznacza kolejkę — za każdym razem.",
    "eyebrow_queue": "CZEGO SKRYPT NIE POTRAFI",
    "queue_h": "Potwierdza kolejkę za ciebie.",
    "eta": "~14 min",
    "confirmed": "twoja kolej — potwierdzone automatycznie",
    "queue_p1": "Aternos otwiera okno na około 30 sekund.",
    "queue_p2": "Przegapisz — wracasz na koniec. aterkeep nie przegapia.",
    "eyebrow_setup": "INSTALACJA, RAZ",
    "login_h": "Bez kopiowania ciasteczek.",
    "f_user": "Nazwa użytkownika Aternos",
    "f_pass": "Hasło Aternos",
    "login_old": "F12 → Network → skopiuj nagłówek cookie",
    "login_new": "Zaloguj się raz. Sesja odnawia się sama co 30 dni.",
    "eyebrow_result": "WYNIK",
    "online_h": "Online. I tak zostaje.",
    "st_online": "ONLINE",
    "st_offline": "OFFLINE",
    "st_queue": "W KOLEJCE",
    "m_players": "GRACZE",
    "eyebrow_what": "CO DOSTAJESZ",
    "f1_t": "Jeden plik",
    "f1_d": "Bez środowiska. Windows, Linux, macOS.",
    "f2_t": "Bot anti-idle",
    "f2_d": "Dołącza, żeby serwer nie został wyłączony.",
    "f3_t": "Szyfrowana sesja",
    "f3_d": "AES-256-GCM, klucza nie ma na dysku.",
    "f4_t": "14 języków",
    "f4_d": "Panel chroniony hasłem, czysty HTTP.",
    "cta_h": "Chcesz?",
    "cta_lic": "Licencja komercyjna, kod dostępny do wglądu.",
    "cta_tos": "Aternos zakazuje botów keep-alive — twoje konto jest zagrożone.",
    "cta_aff": "Bez powiązań z Aternos GmbH ani Mojang Studios.",
}

STRINGS["zh"] = {
    "tagline1": "让你的免费 Aternos 服务器",
    "tagline2": "全天候在线。",
    "eyebrow_problem": "问题",
    "problem_h": "空服务器会被关闭。",
    "problem_p": "想再开，就得重新排队——每一次。",
    "eyebrow_queue": "脚本做不到的事",
    "queue_h": "它替你确认排队。",
    "eta": "约 14 分钟",
    "confirmed": "轮到你了 — 已自动确认",
    "queue_p1": "轮到你时，Aternos 只给约 30 秒的确认窗口。",
    "queue_p2": "错过就排到队尾。aterkeep 从不错过。",
    "eyebrow_setup": "只需设置一次",
    "login_h": "不用复制 Cookie。",
    "f_user": "Aternos 用户名",
    "f_pass": "Aternos 密码",
    "login_old": "F12 → Network → 复制 cookie 请求头",
    "login_new": "登录一次。会话每 30 天自动续期。",
    "eyebrow_result": "结果",
    "online_h": "在线。而且一直在线。",
    "st_online": "在线",
    "st_offline": "离线",
    "st_queue": "排队中",
    "m_players": "玩家",
    "eyebrow_what": "你得到什么",
    "f1_t": "单个文件",
    "f1_d": "无需运行时。Windows、Linux、macOS。",
    "f2_t": "防挂机机器人",
    "f2_d": "自动加入，避免被关闭。",
    "f3_t": "加密会话",
    "f3_d": "AES-256-GCM，磁盘上没有密钥。",
    "f4_t": "14 种语言",
    "f4_d": "密码保护面板，纯 HTTP。",
    "cta_h": "想要吗？",
    "cta_lic": "商业授权，源码可查阅。",
    "cta_tos": "Aternos 规则禁止此类机器人 — 账号存在风险。",
    "cta_aff": "与 Aternos GmbH 或 Mojang Studios 无关。",
}

STRINGS["ja"] = {
    "tagline1": "無料の Aternos サーバーを",
    "tagline2": "24時間オンラインに保ちます。",
    "eyebrow_problem": "問題",
    "problem_h": "空のサーバーは停止されます。",
    "problem_p": "戻すには毎回、待機列に並び直しです。",
    "eyebrow_queue": "スクリプトにできないこと",
    "queue_h": "順番の承認を代わりに行います。",
    "eta": "約14分",
    "confirmed": "順番です — 自動で承認しました",
    "queue_p1": "順番が来ると Aternos は約30秒の承認窓を開きます。",
    "queue_p2": "逃すと最後尾へ。aterkeep は逃しません。",
    "eyebrow_setup": "設定は一度だけ",
    "login_h": "Cookie のコピーは不要。",
    "f_user": "Aternos ユーザー名",
    "f_pass": "Aternos パスワード",
    "login_old": "F12 → Network → cookie ヘッダーをコピー",
    "login_new": "一度ログインするだけ。セッションは30日ごとに自動更新。",
    "eyebrow_result": "結果",
    "online_h": "オンライン。そのまま維持。",
    "st_online": "オンライン",
    "st_offline": "オフライン",
    "st_queue": "待機列",
    "m_players": "プレイヤー",
    "eyebrow_what": "得られるもの",
    "f1_t": "単一ファイル",
    "f1_d": "ランタイム不要。Windows / Linux / macOS。",
    "f2_t": "アンチアイドルボット",
    "f2_d": "参加して停止を防ぎます。",
    "f3_t": "暗号化セッション",
    "f3_d": "AES-256-GCM、鍵はディスクに残りません。",
    "f4_t": "14言語",
    "f4_d": "パスワード保護パネル、純粋な HTTP。",
    "cta_h": "興味ありますか？",
    "cta_lic": "商用ライセンス、ソース閲覧可。",
    "cta_tos": "Aternos の規約はこの種のボットを禁じています — アカウントが危険にさらされます。",
    "cta_aff": "Aternos GmbH や Mojang Studios とは無関係です。",
}

STRINGS["ko"] = {
    "tagline1": "무료 Aternos 서버를",
    "tagline2": "24시간 온라인으로 유지합니다.",
    "eyebrow_problem": "문제",
    "problem_h": "비어 있는 서버는 잠듭니다.",
    "problem_p": "다시 켜려면 매번 대기열입니다.",
    "eyebrow_queue": "스크립트가 못 하는 일",
    "queue_h": "대기열을 대신 확인해 줍니다.",
    "eta": "약 14분",
    "confirmed": "당신 차례 — 자동으로 확인됨",
    "queue_p1": "차례가 오면 Aternos는 약 30초의 창을 엽니다.",
    "queue_p2": "놓치면 맨 뒤로. aterkeep은 놓치지 않습니다.",
    "eyebrow_setup": "설정은 한 번만",
    "login_h": "쿠키 복사 없음.",
    "f_user": "Aternos 아이디",
    "f_pass": "Aternos 비밀번호",
    "login_old": "F12 → Network → cookie 헤더 복사",
    "login_new": "한 번만 로그인. 세션은 30일마다 스스로 갱신됩니다.",
    "eyebrow_result": "결과",
    "online_h": "온라인. 그리고 계속 유지됩니다.",
    "st_online": "온라인",
    "st_offline": "오프라인",
    "st_queue": "대기열",
    "m_players": "플레이어",
    "eyebrow_what": "무엇을 얻나",
    "f1_t": "단일 파일",
    "f1_d": "런타임 불필요. Windows, Linux, macOS.",
    "f2_t": "안티 아이들 봇",
    "f2_d": "접속해서 종료되지 않게 합니다.",
    "f3_t": "암호화된 세션",
    "f3_d": "AES-256-GCM, 디스크에 키 없음.",
    "f4_t": "14개 언어",
    "f4_d": "비밀번호 보호 패널, 순수 HTTP.",
    "cta_h": "필요하신가요?",
    "cta_lic": "상업용 라이선스, 소스 열람 가능.",
    "cta_tos": "Aternos 약관은 이런 봇을 금지합니다 — 계정이 위험합니다.",
    "cta_aff": "Aternos GmbH 또는 Mojang Studios와 무관합니다.",
}

STRINGS["ar"] = {
    "tagline1": "يُبقي خادم Aternos المجاني",
    "tagline2": "متصلاً على مدار الساعة.",
    "eyebrow_problem": "المشكلة",
    "problem_h": "الخوادم الفارغة تُطفأ.",
    "problem_p": "إعادتها تعني الطابور في كل مرة.",
    "eyebrow_queue": "ما لا يستطيعه أي سكربت",
    "queue_h": "يؤكد الطابور نيابةً عنك.",
    "eta": "١٤ دقيقة تقريبًا",
    "confirmed": "جاء دورك — تم التأكيد تلقائيًا",
    "queue_p1": "يفتح Aternos نافذة مدتها نحو ٣٠ ثانية.",
    "queue_p2": "إن فاتتك عدت إلى النهاية. aterkeep لا يفوّتها.",
    "eyebrow_setup": "إعداد لمرة واحدة",
    "login_h": "لا نسخ لملفات الكوكيز.",
    "f_user": "اسم مستخدم Aternos",
    "f_pass": "كلمة مرور Aternos",
    "login_old": "F12 ← Network ← انسخ ترويسة cookie",
    "login_new": "سجّل الدخول مرة واحدة. تتجدد الجلسة كل ٣٠ يومًا تلقائيًا.",
    "eyebrow_result": "النتيجة",
    "online_h": "متصل. ويبقى كذلك.",
    "st_online": "متصل",
    "st_offline": "متوقف",
    "st_queue": "في الطابور",
    "m_players": "اللاعبون",
    "eyebrow_what": "ماذا تحصل",
    "f1_t": "ملف واحد",
    "f1_d": "بلا بيئة تشغيل. ويندوز، لينكس، ماك.",
    "f2_t": "بوت مضاد للخمول",
    "f2_d": "ينضم كي لا يُغلق الخادم.",
    "f3_t": "جلسة مشفّرة",
    "f3_d": "AES-256-GCM، ولا مفتاح على القرص.",
    "f4_t": "١٤ لغة",
    "f4_d": "لوحة محمية بكلمة مرور، HTTP خالص.",
    "cta_h": "هل تريده؟",
    "cta_lic": "ترخيص تجاري مع إتاحة الشيفرة للاطلاع.",
    "cta_tos": "شروط Aternos تمنع هذه البوتات — حسابك في خطر.",
    "cta_aff": "لا صلة له بشركة Aternos GmbH أو Mojang Studios.",
}
